
services:

  cheshire-cat-awesome-plugins-backend:
    build:
      context: .
    container_name: cheshire_cat_awesome_plugins_backend
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - GITHUB_PLUGINS_JSON_URL=${GITHUB_PLUGINS_JSON_URL:-https://raw.githubusercontent.com/cheshire-cat-ai/awesome-plugins/main/plugins.json}
      - DEFAULT_PAGE_SIZE=${DEFAULT_PAGE_SIZE:-10}
      - CACHE_DURATION_MINUTES=${CACHE_DURATION_MINUTES:-1440}
      - RELOAD=${RELOAD:-""}
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - ./:/app
    restart: unless-stopped